name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment when there's a pull request to the main branch

jobs:
  # Job for continuous integration (testing)
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  # Job for deployment
  deploy:
    needs: build  # Ensure deployment only happens after successful build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes CLI (kubectl)
      uses: azure/setup-kubectl@v3

    - name: Authenticate to Kubernetes
      run: |
        kubectl config set-cluster my-cluster --server=<cluster-server>
        kubectl config set-credentials my-user --token=<k8s-token>
        kubectl config set-context my-context --cluster=my-cluster --user=my-user
        kubectl config use-context my-context

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
        kubectl rollout status deployment/frontend
